server:
  port: 8080
spring:

  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 172.17.0.3
    #password:
    port: 6379
  cache:
    redis:
      time-to-live: 1800000
  application:
    name: pet_clinic
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url:  jdbc:mysql://172.17.0.2:3306/pet_clinic
##      url: jdbc:mysql://localhost:3306/pet_clinic
#      username: root
#      password: bFkezjYbzTXR83nJ
##      password: "55039260abcZ"
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://106.14.208.53:3315/pet_clinic?characterEncoding=utf-8
        username: cons_manager
        password: 20240425(cmCM
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://106.15.75.216:3315/pet_clinic?characterEncoding=utf-8
        username: cons_manager
        password: 20240425(cmCM
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
  mapper-locations: com/pet_clinic_end/mapper/*.xml
pet_clinic:
  path: /home/nginx/html/file/
#  path: D:\img\pet\
